modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="shulkerssupersimplestructuresystem" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Shulkers Super Simple Structure System" #mandatory
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
credits="A special thanks to TelepathicGrunt for getting me started on structure generation, and everyone in the Minecraft Worldgen discord for always helping out" #optional
authors="britishnickk aka nhwhite3118" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
I made a simple way to add structures and figured I might as will make it able to read in json to allow everyone to make their own structures.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.shulkerssupersimplestructuresystem]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.shulkerssupersimplestructuresystem]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
